### ISSUE TITLE
Download output : Forbidden

### ISSUE THREAD

**Issue by VikVTor** [Leone25/hub-young-downloader#13]
I followed all the instructions but the output of the download is always "Forbidden". I tried to fix the problem by looking to the calls made by HubYoung but I didn't figured out how to fix the problem.

**Comment by Leone25** [comment]
yes, that i a known issue, unfortunately it seems like they realized they had made a mistake in the configuration and blocked the method the script used to use to download books, if i ever have time i'll take care of fixing it, unless someone else wants to do it.

**Comment by NioBee** [comment]
> it seems like they realized they had made a mistake

😭

**Comment by Leone25** [comment]
There us still a way to download the book, which is to download each page's image and stitch them all together in a pdf, which is not the worst thing ever and not like i haven't done that before, but it's definitely not as good as just having the original pdf... Maybe tho i could explore how the application works, perhaps they still have a way to access the original pdf and it's just hidden better...

**Comment by NioBee** [comment]
I see, but in this case the pdf would be composed by images, so the text in it cannot be extracted, copied and edited outside.. It would be useful to have it when you need to print out a page or two, but not for students in order to make summaries or maps or for vocal recognition..
Of corse you can always extract the text from and image, but then the whole process becomes much more complicated 😵

**Comment by mlahlal** [comment]
I have opened a pull request to resolve this problem. The pdf downloaded allows to extract the text.

**Comment by NioBee** [comment]
Great! Works again flawlessly!! ❤️️
